### ISSUE TITLE
IBM Db2 LUW support

### ISSUE THREAD

**Issue by kovica** [gvenzl/csv2db#1]
Add support for IBM Db2 LUW.
I can test it on IBM Db2 LUW version 10.5, 11.1 on Linux.

**Comment by gvenzl** [comment]
@kovica, DB2 support is now included. I managed to run some smoke tests via the DB2 Docker image on Docker Hub and it manages to load data into the table.

The only question I have is regarding the DSN connect string format.
I currently use `"UID={0};PWD={1};HOSTNAME={2};PORT={3};DATABASE={4};CURRENTSCHEMA={4}"`, note that `DATABASE` and `CURRENTSCHEMA` use the same variable [see here](https://github.com/gvenzl/csv2db/blob/master/src/python/functions.py#L177). 

However, I thought that `CURRENTSCHEMA` wasn't necessary as I specified the `DATABASE` already. But if I don't have `CURRENTSCHEMA` set the INSERT INTO statement defaults to `INSERT INTO <username>.<tablename>` instead of `INSERT INTO <database>.<tablename>`.
I'm not sure what the difference for DB2 is between a database and the current schema, any clues?

Note that I also found a nasty bug in the DB2 Python driver that basically prevents actual error messages to be raised, see https://github.com/ibmdb/python-ibmdb/issues/363. So when debugging any issues you might have to tweak the DB2 Python driver a little (I can show you how if ever necessary).

Let me know whether it works.

**Comment by kovica** [comment]
Thanks, I'll give it a try.
When you connect to Db2 you connect to an actual database, not like MS Server where you connect to server and then you have to specify database in your SQL. So INSERT INTO <username>.<tablename> is the correct form.

**Comment by gvenzl** [comment]
This is what I don't get.
So I have a database created `SAMPLE` and my user is `DB2INST1`.
Then I try to connect to: `UID=DBINST1;PWD=TEST;HOSTNAME=localhost;PORT=50000;DATABASE=SAMPLE`.

The connection is fine but when executing `INSERT INTO STAGING...`, the `STAGING` table residing in the `SAMPLE` database, I receive an error that `INSERT INTO "DB2INST1".STAGING` does not exist.
Which puzzles me because I thought that I already told DB2 that I want to use the `SAMPLE` database and thought that it would not append the user name automatically.

However, if I connect to `UID=DBINST1;PWD=TEST;HOSTNAME=localhost;PORT=50000;DATABASE=SAMPLE;CURRENTSCHEMA=SAMPLE`, the `INSERT` statement works fine. My question here is, what's the difference between `DATABASE` and `CURRENTSCHEMA`. Clearly `DATABASE` does not do what I want it to do, as it is looking for `DB2INST1.STAGING`.

Note, I created the table just using the `db2` command via the `db2inst1` OS user. So I wouldn't see any reason that the table would have been created in a `SAMPLE` schema, unless `DATABASE` and `SCHEMA` are synonymous in that case.

**Comment by kadler** [comment]
In DB2, a database may have multiple schemas and a schema may have multiple tables/views/functions/etc... For unqualified table references, the `CURRENT SCHEMA` is used, which defaults to the name of the logged in user if unspecified.

You could either qualify the table reference (`INSERT INTO DB2INST1.STAGING`) or specify the `CURRENTSCHMEA` connection string keyword.

**Comment by gvenzl** [comment]
Thanks a lot @kadler, sounds like DB2 is just the same as Oracle in that regard then.
And it also sounds like I made a mistake.
Although I connected to the `SAMPLE` database, I connected as the `DB2INST1` user and, rightfully so, DB2 told me that there is no schema `DB2INST1` in the database `SAMPLE`.
So what I'm doing right now is wrong, where I set the `CURRENTSCHEMA` to the same as `DATABASE`, meaning that there always would have to be a a schema inside the database with the same name.

Am I understanding all of that correctly, @kadler?

If so, I basically have to remove `CURRENTSCHEMA` in the DSN string.

**Comment by kadler** [comment]
I'd say so. The user can always qualify the table when passed to the script, eg. 
```
./csv2db load -t myschema.mytable ...
```

**Comment by gvenzl** [comment]
Yeah, that's a good point actually. Thanks a lot!

**Comment by gvenzl** [comment]
Db2 support is now provided with version 1.1.0
