### ISSUE TITLE
Are tabs as separator with no quotes around strings possible 

### ISSUE THREAD

**Issue by SprickW** [gvenzl/csv2db#49]
CSV is fine, but TSV is finer ;-)

I prefer using tabs as separator as tabs are most likely not included in strings. Additionally: When using tabs as separator one doesn't need quotes around strings, which makes some processes easier.

Is it or will it be possible to use csv2db that way?

Greetings to lovely SF

Wolfgang

**Comment by gvenzl** [comment]
Hi @SprickW!

First of all, thank you for your interest in csv2db!

Second, yeah, it is possible. csv2db has a separate option for that, the `-s` or `--separator` parameter.
You can actually pass on any single-character separator, even PSVs (`|`) delimited files are fine and my personal favorite, because they also don't appear often in the text, don't mess with the formatting potentially and are easy to type in the command line. :)

Have a look at [Loading a file with a different column separator](https://github.com/csv2db/csv2db/wiki/User's-Guide#loading-a-file-with-a-different-column-separator), hopefully this is what you are looking for.

Thx and greetings back! :)
